# Generated by Django 4.2.1 on 2023-05-28 08:28

import ads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=200, validators=[ads.validators.check_name]),
        ),
    ]
